sudo: required
services:
  - docker
before_script:
  - docker pull continuumio/miniconda3

before_install:
  - docker build --cache-from continuumio/miniconda3 -t a0987654321/redis_reader -f Dockerfile .

script:
  - docker run a0987654321/redis_reader