sudo: required
services:
  - docker
cache:
  directories:
    - docker-cache

before_script:
  - |
    filename=docker-cache/saved_images.tar
    if [[ -f "$filename" ]]; then docker load < "$filename"; fi
    mkdir -p docker-cache
    docker pull continuumio/miniconda3
    docker save -o "$filename" continuumio/miniconda3

before_install:
  - docker build -t a0987654321/redis_reader -f Dockerfile .

script:
  - docker run a0987654321/redis_reader

language: generic